```yaml id="x9r4lh"
BUILD_AND_PUBLISH:
  needs: Testing
  runs-on: ubuntu-latest

  steps:
    # Checkout Source
    - name: Code Checkout
      uses: actions/checkout@v4

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t $ECR_REPOSITORY:${{ github.run_number }} .
        docker tag $ECR_REPOSITORY:${{ github.run_number }} \
        ${{ secrets.REGISTRY }}/$ECR_REPOSITORY:${{ github.run_number }}

    # Push Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.REGISTRY }}/$ECR_REPOSITORY:${{ github.run_number }}
```
